<?php //[STAMP] 606cafda3b30bd5ba72070122d353e01

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

namespace Plugin_Cinesport_Embed;
use Codeception\Module\IntegrationHelper;

/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method void haveFriend($name, $actorClass = null)
 *
 * @SuppressWarnings(PHPMD)
*/
class IntegrationTester extends \Codeception\Actor
{
   
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Test that the filter definitions passed in have been added where specified.
	 * Example usage:
	 * $my_filters = array(
	 *	'init' => array(
	 *		array( 'BDC_Plugin_Class', 'plugin_function' ),
	 *	),
	 *	'admin_head' => array(
	 *		'standalone_function',
	 *	),
	 * );
	 * \Codeception\Module\UnitHelper::test_filters( $my_filters );
	 * @param array $my_filters The definition of filters to test, as specified
	 * above
     * @see \Codeception\Module\IntegrationHelper::test_filters()
     */
    public function test_filters($my_filters) {
        return $this->scenario->runStep(new \Codeception\Step\Action('test_filters', func_get_args()));
    }
}
